### ISSUE TITLE
PPLCService not found!

### ISSUE THREAD

**Issue by kaixinbuyu** [Whitsoft/GoPlcsockets#1]
def of PPLCService not found?

**Comment by Whitsoft** [comment]
//************************************************************
// Structure for Service                                     *
//************************************************************
type PPLCService *PLCService
type PLCService struct {
Service       byte
ReqPathSize   byte
ReqPath       [4]byte
ReqData       []byte
Seq_Count     uint16
Cmd_Spc_Data  CmdSpcData
}

NOTE: Let me check git to see that the file pl_c.go is included.
I have been meaning to update the code for CompactLogix processors, but I
do not have access to the hardware right now

**Comment by Whitsoft** [comment]
Look for PPLCService in pl_c.go file

**Comment by kaixinbuyu** [comment]
and PLCPtr.CPConnectID not found.
in PLCFunctions.go, line 1339 .
maybe it's an unused code.

**Comment by Whitsoft** [comment]
I'll look at it and get back to you.

**Comment by Whitsoft** [comment]
I modifed the plc_h.go file and  compiled testtcp.go.
It should compile now.
I had made some additions to work with compact logix processors, but do not
have one to test.
I will test the code against a micrologix 1400 in the next few days and let
you know how it works.

**Comment by Whitsoft** [comment]
testtcp.go should compile. I tested the executable with a micrologix 1400
in which I installed testPLC.RSS.
It brings back some data. Use Wireshark to see what is happening.
If it does not work please post a message.

**Comment by kaixinbuyu** [comment]
It works now!Thanks!
